### DISCUSSION TITLE
Cannot tunning simple Gateway for 2 microservices in docker. Please help me

### DISCUSSION THREAD

**Discussion by P9avel** [dotnet/yarp#1780] [General] [answered]
Hello, i think this is very simple issue, but i am cannot solve themself. Please read my description. I am have
1. Payment service
``` c#
namespace Payments.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class PaymentController : ControllerBase
    {
        private readonly ILogger<PaymentController> _logger;

        public PaymentController(ILogger<PaymentController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public string Get()
        {
            return "PaymentService";
        }
    }
}

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

3. Client service
``` c#
using Microsoft.AspNetCore.Mvc;

namespace Clients.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class ClientController : ControllerBase
    {
       private readonly ILogger<ClientController> _logger;

        public ClientController(ILogger<ClientController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public string Get()
        {
            return "ClientService";
        }
    }
}

var builder = WebApplication.CreateBuilder(args);

// Add services to the container.

builder.Services.AddControllers();
// Learn more about configuring Swagger/OpenAPI at https://aka.ms/aspnetcore/swashbuckle
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI();
}

app.UseHttpsRedirection();

app.UseAuthorization();

app.MapControllers();

app.Run();
```

4. Gateway
``` c#
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddReverseProxy()
    .LoadFromConfig(builder.Configuration.GetSection("ReverseProxy"));
var app = builder.Build();
app.MapReverseProxy();
app.Run();
```
``` json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "*",
  "ReverseProxy": {
    "Routes": {
      "payments": {
        "ClusterId": "payments",
        "Match": {
          "Path": "/payments/{**catch-all}"
        }
      },
      "clients": {
        "ClusterId": "clients",
        "Match": {
          "Path": "/clients/{**catch-all}"
        }
      }
    },
    "Clusters": {
      "payments": {
        "Destinations": {
          "destination1": {
            "Address": "https://payment/"
          }
        }
      },
      "clients": {
        "Destinations": {
          "destination1": {
            "Address": "https://client/"
          }
        }
      }
    }
  }
}
```

6. Docker compose running
``` yaml
version: '3.4'

services:
  payments:
    image: ${DOCKER_REGISTRY-}payments
    hostname: payment
    container_name: Payment
    ports:
      - 51001:443
    build:
      context: .
      dockerfile: Payments/Dockerfile

  clients:
    image: ${DOCKER_REGISTRY-}clients
    hostname: client
    container_name: Client
    ports:
      - 51002:443
    build:
      context: .
      dockerfile: Clients/Dockerfile


  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    hostname: gateway
    container_name: Gateway
    ports:
      - 51000:443
    build:
      context: .
      dockerfile: Gateway/Dockerfile
```

When i am running in postman GET https://localhost:51000/payments     
i am reciver 502 badgateway and in Visual studio i am get errors 

``` console
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch, RemoteCertificateChainErrors
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
```
In attach i am put full solution.  Please help me with
1. I need worked solution without this exception
2. I am want to add Swagger and see all APIs

[TestGateway.zip](https://github.com/microsoft/reverse-proxy/files/8994743/TestGateway.zip)
