### DISCUSSION TITLE
Mental Model for Updating YARP Dynamically

### DISCUSSION THREAD

**Discussion by drusellers** [dotnet/yarp#2182] [Q&A] [answered]
```
dotnet 7
YARP 2.0.1
```

I having a pretty good amount of success with YARP, and using the `InMemoryConfigProvider` but I think I have a mental disconnect with how to best use the combination of the File Based configuration and the In-Memory Provider. This is more of a general architectural or organizational question. YARP is working just fine, its my own brain that needs some help.

I'm currently using YARP in a manner where I define the routes in my appsettings file (included below). I then later want to use a service discovery mechanism to find matching destinations. I query my service discovery, I find some instances, then I create the Cluster with CusterId `Demo` and populate it with Destinations. When I call the `Update(routes, clusters)` I get an error because the cluster `Demo` already exists, from the config file and I can't add another cluster with the same Id. I was hoping that they would get merged, but that doesn't seem to be the case.

With that kind of context in mind, I'm curious about a broader scoped question about how to best use YARP. I'm starting to think that once you go "dynamic" you really want the whole thing to be dynamic. Specifically meaning that if I'm using In-Memory I should probably do all of it using the InMemory provider to avoid this kind of collision.

Any ways,

Thank you.

appsettings.yaml

```
ReverseProxy:
  Routes:
    Demo:
      ClusterId: Demo
      Match:
        Path: "/demo/{**catch-all}"
      Transforms:
        - PathRemovePrefix: "/demo"
  Clusters:
    Demo:
      HealthCheck:
        Active:
          Enabled: "true"
          Interval: "00:00:10"
          Timeout: "00:00:10"
          Path: "/health"
```
